### ISSUE TITLE
Need to build libconfuse 2.8

### ISSUE THREAD

**Issue by fhunleth** [bordeltabernacle/vagrant-nerves#2]
I noticed that you installed libconfuse 2.7 in your script. If you were to run `make check` in the fwup build directory, you'll get some test failures. See https://github.com/martinh/libconfuse/releases/tag/v2.8 for libconfuse 2.8. The fwup README.md also has information on this. Note that you'll also need to run `sudo apt-get install mtools unzip` for the fwup regression tests to work.

**Comment by bordeltabernacle** [comment]
Right, I misunderstood, I assumed `libconfuse` wasn't available at all through apt, and so when I was able to install it I assumed that had changed, rather than that it installed the wrong version.  Thanks for the heads up! :+1:

**Comment by bordeltabernacle** [comment]
I had to install `zip` as well for the tests to pass
